### ISSUE TITLE
SystVnVPlan - Typos and minor formatting errors

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#10]
I found a few typos and minor formatting errors in the SystVnVPlan, listed below:

- In the purpose of document section (pg 1), in the first sentence, "(V&V)" should appear before the word "plan" since "plan" is not included in the acronym
- In the same sentence, the LoSMS acronym should appear after the full typed-out name of the software. i.e. "LoSMS (Library of Simplex Method Solvers)" should instead say "Library of Simplex Method Solvers (LoSMS)"
- In the last sentence of the same section, "Finally, the document is concluded" is redundant. This can be shortened by removing the word "Finally" or rephrasing to not include the word "concluded"
- In Section 5.1.2, T5, there is a typo in the first linear constraint: "-1x<sub>1</sub>" should just be "-x<sub>1</sub>"

**Comment by hananezlitni** [comment]
Thank you Brooks. I applied the comments.
