### ISSUE TITLE
SystVnVPlan - Symbols missing from Table of Symbols

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#11]
There are some symbols used in the document that are not defined in the "Symbols, Abbreviations, and Acronyms" section of the SystVnVPlan. For example, _Z_ , _x<sub>1</sub>_, _x<sub>2</sub>_, etc.

Two potential fixes:
1. These symbols should be added to the "Symbols, Abbreviations, and Acronyms" section of the SystVnVPlan, or 
2. They should be added to the "Table of Symbols" in the CA, since these symbols are also used in the CA, and then the "Table of Symbols" from the CA should be referenced in the "Symbols, Abbreviations, and Acronyms" section of the SystVnVPlan.

If you choose to reference the CA table of symbols, be careful because the acronym "T" stands for "Theoretical Model" in the CA but "Test" in the SystVnVPlan, so you may need to change one of those acronyms, or make it clear that the acronyms in the SystVnVPlan table override any acronyms from the CA.

**Comment by smiths** [comment]
@bmaclach - great attention to detail!

**Comment by hananezlitni** [comment]
Added the missing symbols.. thank you Brooks! (:
