### ISSUE TITLE
SystVnVPlan - More details for "Plan" section

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#12]
In Section 4 of the SystVnVPlan ("Plan" section), specifically sections 4.2, 4.3, and 4.4, there could be more detail about how the feedback from Dr. Smith and the CAS 741 class will be handled. 

For example, the feedback from the CAS 741 students comes from formal reviews of the documents, and the feedback is expressed as issues on GitHub for you act on. If this were explicitly mentioned in each section, it would be more clear how the SRS, design, and implementation are being verified.

**Comment by hananezlitni** [comment]
Thank you for the suggestions (: Added more details in the "Plan" section.
