### ISSUE TITLE
SystVnVPlan - Test case for multiple solutions for minimization?

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#13]
The minimization test cases in Section 5.1.2 seem to follow the pattern of the maximization test cases in Section 5.1.1, but there is no test case for multiple solutions for minimization. Is there a reason for that?

If there is a reason, maybe there should be a short description at the beginning of Section 5.1.1 explaining why the test cases provide sufficient coverage of minimization with LoSMS. Otherwise, I think this additional test case should be added.

**Comment by hananezlitni** [comment]
Thank you!
