### ISSUE TITLE
SystVnVPlan - Comments about Usability Survey

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#14]
The question at the end of the usability survey "Please provide us with general comments, if any" is very important because it should tell you specifically where you need to make a change if the usability is not good enough. However, if the participant chooses not to answer this question, you may not know what course of action to take based only on their ratings in the previous questions. 

Therefore, I might think about changing the wording of the final question to encourage the participant to explain any bad ratings. Something like, "Please provide reasons for your above responses" might work better. 

Even better, in my opinion, would be to ask for comments after each question on the survey. That way, the comments apply specifically to a single question and the participant has more guidance on what they should be commenting on.

**Comment by hananezlitni** [comment]
Done. Thank you for your suggestion.
