### ISSUE TITLE
SystVnVPlan - Add specifics for correctness and performance test cases

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#15]
In section 5.2.4, the exact problem you will use to compare LoSMS and MatLab should be provided (i.e. specify which inputs will be used), so that someone else would be able to carry out the test case if given the plan.

I would also suggest splitting this up into two separate tests, one for correctness and one for performance. That way, if a test fails, the reason for the failure is clear (in its current form, if the test fails you would not know if the correctness or the performance of LoSMS was the issue).

**Comment by hananezlitni** [comment]
Thank you! Closed by e9c6e7b.
