### ISSUE TITLE
SystVnVPlan - Add specifics for stability test case

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#16]
The stability test case in Section 5.2.5 should have more detail so that another person would be able to carry it out if given the plan. Specifically, the following questions should be answered in the test case description:

- What is meant by "great number of inputs" in this case? Is it the number of linear constraints, or the number of parameters in the objective function? Would it make sense to split this into 2 test cases, one for linear constraints and one for parameters?
- Exactly how many inputs is a "great number"? Specifying not only the exact number of inputs but also the inputs themselves would be even better.

**Comment by hananezlitni** [comment]
Thank you! Closed by e9c6e7b.
