### ISSUE TITLE
MG review - Completeness issue 

### ISSUE THREAD

**Issue by vajihehm** [hananezlitni/HZ-CAS741-Project#18]
@hananezlitni Please add table Abbreviations and Acronyms which Dr. Smith has added in the template for MG , SRS, SC and other terms which you used in your documents as abrevation or acronym.

**Comment by vajihehm** [comment]
@hananezlitni I did not make sense of AC4 “The assumptions related to the input data.” as Anticipated Change. If you mean format of the input parameters external to the Driver Program please clarify it. ( Regarding to the CA I did not undrestand if user inputs data or not. Dr smith has commented the user does not input data.)

**Comment by vajihehm** [comment]
@hananezlitni Is there a specific reason which you considered a sepearte module for “Input Conversion Module”. Is it possible you merge this module into “input” Module.

**Comment by vajihehm** [comment]
@hananezlitni Please the UC2 be paraphrased. It is somewhat ambiguous. You should use “in order to” instead of  “to” as Dr.smith has mentioned.

**Comment by vajihehm** [comment]
@hananezlitni According to the input Module (M2) "Gets the inputs from the client, verifies that they are valid, throws an error if the inputs violate any constraints" I think it should be a Behaviour-Hiding Module. Besides, M8 Module output Module should be a Behaviour-Hiding Module.

**Comment by hananezlitni** [comment]
@vajihehm Done. Thank you for the comment.
