### ISSUE TITLE
For ProblemStatement.tex use 80 character width

### ISSUE THREAD

**Issue by smiths** [hananezlitni/HZ-CAS741-Project#2]
The text for your ProblemStatement.tex file is better set to an 80 character width.  As you make changes the diffs are much easier to see if the lines have a fixed length.  Your editor should support fixed width lines.  (Hard wrap, not soft wrap.)

**Comment by hananezlitni** [comment]
Done. I set the tex file width to 80 characters per line in the following commit: 7e35303e3b82e93132258ea5a1732a42eea848e3

**Comment by smiths** [comment]
The commit looks different, but it doesn't look like the width is 80 characters.  You might want to check  your text editor.  For mine (Aquamacs - emacs for Macs), I need to explicitly tell it to auto-fill to reformat a paragraph.

**Comment by hananezlitni** [comment]
I noticed that there were multiple line breaks in the tex file which made it look like the width isn't 80 characters. I fixed it in c017b9a4602821f3ef6f70337a307789c88a7fdf

**Comment by smiths** [comment]
That does look better @hananezlitni.
