### ISSUE TITLE
MG review - Behaviour Hiding

### ISSUE THREAD

**Issue by vajihehm** [hananezlitni/HZ-CAS741-Project#22]
@hananezlitni According to the input Module (M2) "Gets the inputs from the client, verifies that they are valid, throws an error if the inputs violate any constraints" I think it should be a Behaviour-Hiding Module. Besides, M8 Module output Module should be a Behaviour-Hiding Module.

**Comment by hananezlitni** [comment]
@vajihehm When I discussed this with Dr. Smith, it turned out since my project is a library that provides services, all modules should be under software decision modules, including the input and output modules. Thank you for your comment.
