### ISSUE TITLE
CA Completed for Review

### ISSUE THREAD

**Issue by hananezlitni** [hananezlitni/HZ-CAS741-Project#3]
The commonality analysis is completed for review.

Thank you.

**Comment by smiths** [comment]
@hananezlitni thank you for the update.  I'll get to the review as soon as I can.

**Comment by smiths** [comment]
Some initial thoughts on the CA are given in 5b7497c.

**Comment by hananezlitni** [comment]
@smiths Thank you Dr. Smith. I will apply the comments as soon as possible.

**Comment by smiths** [comment]
@hananezlitni, I've completed my review.  You can find my comments in d8f02a6.
