### ISSUE TITLE
UnitVnV Plan - Minor formatting issues

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#31]
Most of these are admittedly very minor, but here are some formatting issues I found with the UnitVnVPlan:

- The acronym T is used for both Theoretical Model in the CA and Test in the VnVPlan. This only matters because you refer to the CA acronyms table in the Unit VnV Plan, so the acronym becomes ambiguous. But also you never use both acronyms in the same document so it is probably fine.
- V&V and MIS are missing from the table of acronyms.
- In the first line of the introduction, "verification and validation" should be "Verification and Validation" so that the letters that correspond with the acronym are capitalized.
- Same for "module interface specification" in the fourth line.
- The acronym "V&V" is used for the Unit V&V Plan but "VnV" is used for the System VnV Plan. This could be made consistent.
- In the 2nd sentence of section 5.1.3, "min" and "max" could be replaced with "minimization" and "maximization" since those abbreviations are not defined formally in the table of abbreviations.
- Just a suggestion, but when you refer to test cases and sections of the System VnV Plan, you could use the LaTeX package "xr" for making references to external documents, to make it easier to maintain.

**Comment by hananezlitni** [comment]
Applied all comments. Thank you very much @bmaclach.
