### ISSUE TITLE
UnitVnV Plan - Test Coverage

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#34]
It seems like there are some cases that are not covered by tests. For example, the case in the Simplex solver module where there is an exception. Also, some access programs like the TableauT access program in the Simplex solver module are not covered. For completeness, tests should be added to cover these. Or, you could add some text to the beginning of each subsection in Section 5 explaining how the tests cover everything or why some cases were not prioritized for testing.

**Comment by hananezlitni** [comment]
Done. Thank you!
