### ISSUE TITLE
UnitVnV Plan - Minimality of test cases

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#35]
Some of the test cases make multiple asserts, and you may want to split these up into multiple test cases to make them minimal. Some examples are:

- T2 could be a test case for the matrix transition and a separate test case for the wasMin transition
- T4 and T5 could each be split into a test case for Z and a test case for K

**Comment by hananezlitni** [comment]
Thank you for the suggestion. Comment applied.
