### ISSUE TITLE
UnitVnV Plan - Question about T2 output

### ISSUE THREAD

**Issue by bmaclach** [hananezlitni/HZ-CAS741-Project#36]
In T2 of the UnitVnVPlan, shouldn't the first row of the matrix be multiplied by -1 in the output? From the MIS it looks like that should always happen when the goal is minimization, but maybe I am misunderstanding?

**Comment by hananezlitni** [comment]
@bmaclach You are correct. I forgot to negate the first row. Thank you very much!
