### ISSUE TITLE
Questions for assumptions section.

### ISSUE THREAD

**Issue by PeaWagon** [hananezlitni/HZ-CAS741-Project#4]
1. What assumptions are made about the objective function in order for it to be solvable? What space does it occupy?

2. In A1, Sn is required to be positive. However, Sn is positive by definition (as stated in DD3). Does this count as an assumption? Is there an input that the user can provide whereby the Sn is negative and a valid answer can still be found?

**Comment by hananezlitni** [comment]
**1. What assumptions are made about the objective function in order for it to be solvable? What space does it occupy?**

The objective function ∈ R.. I will add it as an assumption to avoid any confusions.

**2. In A1, Sn is required to be positive. However, Sn is positive by definition (as stated in DD3). Does this count as an assumption? Is there an input that the user can provide whereby the Sn is negative and a valid answer can still be found?**

The function cannot be solved if Sn and Xn (the decision variables) are negative. Do you think I should remove this assumption? I added it so I can make it clear that they should be positive.
**Update:** I removed this assumption as it is stated in other sections of the document that the decision and slack variables are required to be positive.

**Comment by hananezlitni** [comment]
6e31a5c applies the comments in this issue.

**Affected sections:** 6.2

Closing.
