### ISSUE TITLE
Formatting for Theory Section

### ISSUE THREAD

**Issue by PeaWagon** [hananezlitni/HZ-CAS741-Project#6]
T1/T2 - what is the relationship between the c's and the a's? They should be defined somewhere.

T3 - I would redefine the row switching, row addition, and row multiplication to use subscripts i and j to indicate any two rows (right now it looks as if you can only chose row 1 and row n). If only the first and nth rows should be chosen, disregard this comment.

The subscripts for DD2 do not match up with what is in the theory section with respect to rows and columns.

**Comment by hananezlitni** [comment]
Thank you for your feedback. I applied all your comments in the theoretical models.

**Comment by hananezlitni** [comment]
6e31a5c applies the comments in this issue.

**Affected sections:** 2.2, 5.3, 5.5 and 6.1

Closing.
