### ISSUE TITLE
Requests for further clarification on definitions

### ISSUE THREAD

**Issue by PeaWagon** [hananezlitni/HZ-CAS741-Project#7]
From Section 4.1 under the user responsibilities, you mention that the user must provide the objective function goal. Does this simply mean that the user must specify whether they wish to maximise or minimise the objective function? If yes, perhaps include this as part of your definitions section (or state explicitly in requirements R6).

Can you give an example of a linear constraint? Or perhaps include in section 5.2.

For the terminology & definitions section 5.2, you give that decision variables are x1 through to xn. Is it possible to further define this set of variables?

**Comment by hananezlitni** [comment]
**1. From Section 4.1 under the user responsibilities, you mention that the user must provide the objective function goal. Does this simply mean that the user must specify whether they wish to maximise or minimise the objective function? If yes, perhaps include this as part of your definitions section (or state explicitly in requirements R6).**

Yes. I added a definition of the objective function goal in section 5.2.

**2. Can you give an example of a linear constraint? Or perhaps include in section 5.2.**

I added a definition of the linear constraints and provided examples in section 5.2.

**3. For the terminology & definitions section 5.2, you give that decision variables are x1 through to xn. Is it possible to further define this set of variables?**

I further defined the decision variables in section 5.2.

**Comment by hananezlitni** [comment]
6e31a5c applies the comments in this issue.

**Affected sections:** 5.2

Closing.
