### ISSUE TITLE
Random comments

### ISSUE THREAD

**Issue by PeaWagon** [hananezlitni/HZ-CAS741-Project#8]
- The title of document should also probably include CA.
- In the introduction, CA is explicitly defined, but LoSMS is not.
- IM1 describes the algorithm for maximising the objective function, but the description does not include an overview of the purpose of the IM or what it is doing beyond maximisation. 
- I'm not sure what the point of section 6.4 is. Maybe you can give an example of the output explicitly. 
- In what case do you expect multiple solutions? When is there no solution?
- Clarify the form of Z. Is Z a matrix, function, or value, or is it something else?
- Perhaps in the introduction you could mention why this method is good compared to other linear programming techniques. Justify your choice of the simplex method.

Also just wanted to mention that you did a good job with the document :) I've never taken a linear programming course before, so please excuse any ignorant questions.

**Comment by hananezlitni** [comment]
I have applied all your comments.

- **In what case do you expect multiple solutions? When is there no solution?**

You can't tell from the inputs if there would be multiple solutions or no solution. It depends on the function and constraints that the tool is solving. The solution will be clear after the tool performs the row operations in the simplex tableau.

**Also just wanted to mention that you did a good job with the document :) I've never taken a linear programming course before, so please excuse any ignorant questions.**

Thank you very much (: and thank you for your comments.. they were helpful!

**Comment by hananezlitni** [comment]
6e31a5c applies the comments in this issue.

**Affected sections:** cover page, 3, 6.1 and 6.4

Closing.
